### PR TITLE
Smart wallet address abstraction

### PR DESCRIPTION
**Pull request by nerfZael**
API mode now has dev and non-dev mode.
`-d --dev` to start api in dev mode
In dev mode the safe smart wallet is used (either the SMART_ACCOUNT_ADDRESS or a dev_account)
In non-dev mode (default) the address is expected to be provided when POSTing to the `/api/v1/task` endpoint
Both async (`await autotx.a_run`) and sync (`autotx.run`) modes of autotx run are supported

### CODE REVIEW

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/send,agents/token/send

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/send

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py,agents/token/test_swap_and_send.py

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/research 1

**Review by dOrgJelli — APPROVED** [review]

**Review by cbrzn — APPROVED** [review]

**Pull request merged**
