### PR TITLE
Complex swap test 

### PR DESCRIPTION
**Pull request by nerfZael**

### CODE REVIEW

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py 10

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py::test_auto_tx_swap_complex_1,agents/token/test_swap.py::test_auto_tx_swap_complex_2 30

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py::test_auto_tx_swap_complex_1,agents/token/test_swap.py::test_auto_tx_swap_complex_2 30

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py::test_auto_tx_swap_complex_1 30

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py::test_auto_tx_swap_complex_1 30

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py 30

**Comment by nerfZael** [comment]
python benchmarks.py agents/token/test_swap.py 30

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py::test_auto_tx_swap_complex_1,agents/token/test_swap.py::test_auto_tx_swap_complex_2 30

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py::test_auto_tx_swap_complex_1,agents/token/test_swap.py::test_auto_tx_swap_complex_2 30

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/ 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py 5

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap_and_send.py 5

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap_and_send.py 5

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap_and_send.py

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap_and_send.py

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token 6

**Comment by nerfZael** [comment]
/workflows/benchmarks autotx/tests/agents/token/research/test_research.py 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/research/test_research.py 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py,agents/token/test_swap_and_send.py 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap_and_send.py 10

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/test_swap.py::test_auto_tx_swap_multiple 1

**Review by dOrgJelli — APPROVED** [review]

**Pull request merged**
