### PR TITLE
CI benchmarks testing

### PR DESCRIPTION
**Pull request by nerfZael**
Using this PR to test CI benchmarks
Also removed some extra whitespace

### CODE REVIEW

**Comment by nerfZael** [comment]
/workflows/ci

**Comment by nerfZael** [comment]
/workflows/ci

**Comment by nerfZael** [comment]
/workflows/ci

**Comment by nerfZael** [comment]
/workflows/ci

**Comment by nerfZael** [comment]
/workflows/benchmarks agents/token/send/test_send.py::test_auto_tx_send_eth 2

**Review by cbrzn — APPROVED** [review]

**Pull request merged**
